series: Basic C++
title: Headers
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use header files to organize your code.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Basic C++
    title: Flow Control